# DashboardAgent for SOLAR-PAMPA
# Reads predictions, metrics, and features
# Generates the Streamlit dashboard at dashboard/app.py
# Run dashboard with: streamlit run dashboard/app.py

import pandas as pd
import json
import shutil
from pathlib import Path
from agents import BaseAgent
from config import FIGURES_DIR, LOCATION_NAME, LATITUDE, LONGITUDE


class DashboardAgent(BaseAgent):

    def __init__(self, input_path: Path, output_path: Path):
        super().__init__(
            name        = "DashboardAgent",
            input_path  = input_path,
            output_path = output_path
        )
        self.predictions_file = Path("models") / "predictions.parquet"
        self.metrics_file     = self.input_path  / "metrics.json"
        self.features_file    = Path("data") / "processed" / "features_weekly.parquet"
        self.app_file         = self.output_path / "app.py"

    def validate_inputs(self) -> bool:
        missing = []
        for f in [self.predictions_file, self.metrics_file, self.features_file]:
            if not f.exists():
                missing.append(str(f))

        if missing:
            self.logger.error(f"Missing input files: {missing}")
            return False

        self.logger.info("All input files found")
        return True

    def run(self) -> bool:
        self.logger.info("Writing Streamlit dashboard...")
        self._write_app()
        self.logger.info(f"Dashboard written to: {self.app_file}")
        self.logger.info("Run with: streamlit run dashboard/app.py")
        return True

    # ------------------------------------------------------------------
    # Write app.py
    # ------------------------------------------------------------------
    def _write_app(self):
        """Generate the full Streamlit app as a Python file."""

        app_code = '''# SOLAR-PAMPA Dashboard
# Generated by DashboardAgent
# Run with: streamlit run dashboard/app.py

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import json
from pathlib import Path

# --- Page Config ---
st.set_page_config(
    page_title  = "SOLAR-PAMPA Dashboard",
    page_icon   = "☀️",
    layout      = "wide",
    initial_sidebar_state = "expanded"
)

# --- Paths ---
ROOT         = Path(__file__).parent.parent
PREDICTIONS  = ROOT / "models"  / "predictions.parquet"
METRICS      = ROOT / "reports" / "metrics.json"
FEATURES     = ROOT / "data"    / "processed" / "features_weekly.parquet"

# --- Load Data ---
@st.cache_data
def load_data():
    predictions = pd.read_parquet(PREDICTIONS)
    predictions["week_start"] = pd.to_datetime(predictions["week_start"])

    features = pd.read_parquet(FEATURES)
    features["week_start"] = pd.to_datetime(features["week_start"])

    with open(METRICS) as f:
        metrics = json.load(f)

    return predictions, features, metrics

predictions, features, metrics = load_data()

# --- Sidebar ---
st.sidebar.image("https://flagcdn.com/w80/ar.png", width=60)
st.sidebar.title("☀️ SOLAR-PAMPA")
st.sidebar.markdown("**La Pampa, Argentina**")
st.sidebar.markdown("---")

date_min = predictions["week_start"].min().date()
date_max = predictions["week_start"].max().date()

start_date, end_date = st.sidebar.date_input(
    "Select date range",
    value   = [date_min, date_max],
    min_value = date_min,
    max_value = date_max
)

st.sidebar.markdown("---")
show_ci = st.sidebar.checkbox("Show confidence interval", value=True)
show_features = st.sidebar.checkbox("Show feature data", value=False)

# --- Filter ---
mask = (
    (predictions["week_start"].dt.date >= start_date) &
    (predictions["week_start"].dt.date <= end_date)
)
df = predictions[mask].copy()

# --- Header ---
st.title("☀️ SOLAR-PAMPA — Solar Forecasting Dashboard")
st.markdown(f"**Location:** {''' + repr(LOCATION_NAME) + '''} | "
            f"**Lat:** {''' + str(LATITUDE) + '''} | "
            f"**Lon:** {''' + str(LONGITUDE) + '''}")
st.markdown("---")

# --- Metrics Row ---
col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("MAE",       f"{metrics[\'mae\']:.3f} kWh/m²")
col2.metric("RMSE",      f"{metrics[\'rmse\']:.3f} kWh/m²")
col3.metric("MAPE",      f"{metrics[\'mape_pct\']:.1f}%")
col4.metric("R²",        f"{metrics[\'r2\']:.3f}")
col5.metric("CI Coverage", f"{metrics[\'ci_coverage_pct\']:.1f}%")

st.markdown("---")

# --- Forecast Chart ---
st.subheader("📈 Weekly Solar Output: Forecast vs Actual")

fig = go.Figure()

if show_ci:
    fig.add_trace(go.Scatter(
        x    = pd.concat([df["week_start"], df["week_start"][::-1]]),
        y    = pd.concat([df["upper_bound"], df["lower_bound"][::-1]]),
        fill = "toself",
        fillcolor = "rgba(70,130,180,0.2)",
        line = dict(color="rgba(255,255,255,0)"),
        name = "95% Confidence Interval"
    ))

fig.add_trace(go.Scatter(
    x     = df["week_start"],
    y     = df["actual"],
    mode  = "lines",
    name  = "Actual",
    line  = dict(color="black", width=2)
))

fig.add_trace(go.Scatter(
    x     = df["week_start"],
    y     = df["predicted"],
    mode  = "lines",
    name  = "Predicted",
    line  = dict(color="steelblue", width=2, dash="dash")
))

fig.update_layout(
    xaxis_title = "Week",
    yaxis_title = "GHI (kWh/m²)",
    hovermode   = "x unified",
    height      = 420,
    legend      = dict(orientation="h", y=1.1)
)

st.plotly_chart(fig, use_container_width=True)

# --- Map ---
st.subheader("🗺️ Target Region — La Pampa, Argentina")

map_fig = px.scatter_mapbox(
    lat        = [-37.5],
    lon        = [-66.5],
    zoom       = 5,
    height     = 380,
    size       = [20],
    color_discrete_sequence = ["red"]
)
map_fig.update_layout(
    mapbox_style = "open-street-map",
    margin       = dict(r=0, t=0, l=0, b=0)
)
st.plotly_chart(map_fig, use_container_width=True)

# --- Residuals ---
st.subheader("📊 Residual Analysis")

col1, col2 = st.columns(2)

with col1:
    res_fig = px.line(
        df, x="week_start", y="residual",
        title = "Residuals Over Time",
        labels = {"residual": "Residual (kWh/m²)", "week_start": "Week"}
    )
    res_fig.add_hline(y=0, line_dash="dash", line_color="black")
    st.plotly_chart(res_fig, use_container_width=True)

with col2:
    hist_fig = px.histogram(
        df, x="residual", nbins=30,
        title  = "Residual Distribution",
        labels = {"residual": "Residual (kWh/m²)"}
    )
    hist_fig.add_vline(x=0, line_dash="dash", line_color="black")
    st.plotly_chart(hist_fig, use_container_width=True)

# --- Feature Data ---
if show_features:
    st.subheader("🔬 Feature Data")
    feat_mask = (
        (features["week_start"].dt.date >= start_date) &
        (features["week_start"].dt.date <= end_date)
    )
    st.dataframe(
        features[feat_mask].set_index("week_start"),
        use_container_width=True
    )

st.markdown("---")
st.caption("SOLAR-PAMPA | Solar Output Logistics & Atmospheric Response Prediction")
'''

        with open(self.app_file, "w", encoding="utf-8") as f:
            f.write(app_code)